[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/corazzon/finance-data-analysis/blob/main/5.2%20%EC%97%85%EC%A2%85%20%ED%85%8C%EB%A7%88%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%A0%84%EC%B2%98%EB%A6%AC-input.ipynb)

## 업종/테마 전처리 미션확인

* 팀장님이 우리 회사와 유사한 업종과 테마로 사업을 하고 있는 종목을 수집해서 분석해 달라는 미션을 주셨습니다.
* 코스피에서 해당 업종 혹은 테마의 시가총액이 가장 많은 종목을 찾아주세요.
* 해당 업종/테마의 거래량이 가장 많은 종목을 찾아주세요.
* 최근 52주 최고가에서 현재가 기준으로 가장 손실이 크게 난 종목은 어떤 종목일까요?
* 거래대금이 20위 안에 있는 코스피 종목 중에 "PER"가 가장 낮은 종목은 무엇일까요?


### 주요 업종/테마

* 실습에 참고해 보세요.
* 제약 업종 : https://finance.naver.com/sise/sise_group_detail.nhn?type=upjong&no=35
* 의료기기 : https://finance.naver.com/sise/sise_group_detail.nhn?type=theme&no=175
* 코로나19(덱사메타손) : https://finance.naver.com/sise/sise_group_detail.nhn?type=theme&no=442
* 제약업체 : https://finance.naver.com/sise/sise_group_detail.nhn?type=theme&no=172
* 바이오시밀러(복제 바이오의약품) : https://finance.naver.com/sise/sise_group_detail.nhn?type=theme&no=241

In [1]:
# 라이브러리 로드하기 : 데이터 분석을 위한 pandas, 수치계산을 위한 numpy
import pandas as pd
import numpy as np

In [4]:
# 4.업종/테마주 수집시에 저장해 두었던 csv 파일을 다시 읽어오기
# 'upjong_no_26_연-월-일.csv'
# 종목코드는 꼭 문자형태로 불러오기. dtype={"종목코드":np.object}
file_name = "upjong_no_261_2024-05-12.csv"
raw = pd.read_csv(file_name, dtype={"종목코드":np.object})
raw.shape

C:\Users\user\AppData\Local\Temp\ipykernel_17704\1754562375.py:5: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  raw = pd.read_csv(file_name, dtype={"종목코드":np.object})

(164, 50)

In [5]:
# 미리보기
raw.head()

,종목명,현재가,전일비,등락률,매수호가,매도호가,거래량,거래대금,전일거래량,조회일자,...,배당수익률,동일업종 PER,동일업종 등락률,배당수익률l2023.12,배당수익률l2024.02,PERlEPS(2024.02),PBRlBPS (2024.02),배당수익률l2024.03,배당수익률l2024.01,배당수익률l2024.04
0,한국유니온제약 *,6220.0,상승 410,+7.06%,6220.0,6230.0,30120.0,184.0,7041.0,2024-05-12,...,NaN,101.57배,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,에이비온 *,8200.0,상승 490,+6.36%,8190.0,8200.0,240152.0,1946.0,171467.0,2024-05-12,...,NaN,101.57배,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,에이프로젠바이오로직스,1631.0,상승 90,+5.84%,1631.0,1632.0,498832.0,802.0,155279.0,2024-05-12,...,NaN,101.57배,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,광동헬스바이오,2710.0,상승 105,+4.03%,2610.0,2675.0,2.0,5.0,891.0,2024-05-12,...,NaN,101.57배,+0.31%,0.48%,NaN,NaN,NaN,NaN,NaN,NaN
4,대봉엘에스 *,10450.0,상승 400,+3.98%,10440.0,10450.0,203025.0,2095.0,84220.0,2024-05-12,...,NaN,101.57배,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 전체 컬럼 출력하기

In [6]:
# 전체 컬럼이 출력되도록 display 설정을 변경
pd.options.display.max_columns = None

In [7]:
# 전체 컬럼이 보이는지 확인
raw.head()

,종목명,현재가,전일비,등락률,매수호가,매도호가,거래량,거래대금,전일거래량,조회일자,종목명_전처리,종목코드,매출액,영업이익,당기순이익,영업이익률,순이익률,ROE(지배주주),부채비율,당좌비율,유보율,EPS(원),PER(배),BPS(원),PBR(배),주당배당금(원),시가배당률(%),배당성향(%),시가총액,시가총액순위,상장주식수,액면가l매매단위,외국인한도주식수(A),외국인보유주식수(B),외국인소진율(B/A),투자의견l목표주가,52주최고l최저,PERlEPS(2023.12),추정PERlEPS,PBRlBPS (2023.12),배당수익률,동일업종 PER,동일업종 등락률,배당수익률l2023.12,배당수익률l2024.02,PERlEPS(2024.02),PBRlBPS (2024.02),배당수익률l2024.03,배당수익률l2024.01,배당수익률l2024.04
0,한국유니온제약 *,6220.0,상승 410,+7.06%,6220.0,6230.0,30120.0,184.0,7041.0,2024-05-12,한국유니온제약,080720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,492 억원,코스닥 1344위,7909829,500원 l 1주,7909829,53729,0.68%,N/A l N/A,"6,460 l 4,210","N/A l -2,297원",N/A l N/A,"1.48배 l 4,196원",NaN,101.57배,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,에이비온 *,8200.0,상승 490,+6.36%,8190.0,8200.0,240152.0,1946.0,171467.0,2024-05-12,에이비온,203400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,806 억원",코스닥 498위,22025993,500원 l 1주,22025993,68933,0.31%,N/A l N/A,"9,720 l 4,710","N/A l -1,524원",N/A l N/A,18.10배 l 453원,NaN,101.57배,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,에이프로젠바이오로직스,1631.0,상승 90,+5.84%,1631.0,1632.0,498832.0,802.0,155279.0,2024-05-12,에이프로젠바이오로직스,003060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,086 억원",코스피 887위,66575468,500원 l 1주,66575468,374036,0.56%,N/A l N/A,"6,927 l 1,467","N/A l -1,838원",N/A l N/A,"0.29배 l 5,607원",NaN,101.57배,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,광동헬스바이오,2710.0,상승 105,+4.03%,2610.0,2675.0,2.0,5.0,891.0,2024-05-12,광동헬스바이오,086220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,159 억원",코스닥 753위,11086579,500원 l 1주,11086579,203906,1.84%,N/A l N/A,"14,950 l 7,580",27.72배 l 377원,N/A l N/A,"0.95배 l 11,027원",NaN,101.57배,+0.31%,0.48%,NaN,NaN,NaN,NaN,NaN,NaN
4,대봉엘에스 *,10450.0,상승 400,+3.98%,10440.0,10450.0,203025.0,2095.0,84220.0,2024-05-12,대봉엘에스,078140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,932 억원",코스닥 455위,98867465,NaN,98867465,1221029,1.24%,N/A l N/A,"3,140 l 1,180",N/A l -540원,N/A l N/A,2.58배 l 757원,NaN,101.57배,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# DataFrame의 column만 보기
raw.columns

Index(['종목명', '현재가', '전일비', '등락률', '매수호가', '매도호가', '거래량', '거래대금', '전일거래량',
       '조회일자', '종목명_전처리', '종목코드', '매출액', '영업이익', '당기순이익', '영업이익률', '순이익률',
       'ROE(지배주주)', '부채비율', '당좌비율', '유보율', 'EPS(원)', 'PER(배)', 'BPS(원)',
       'PBR(배)', '주당배당금(원)', '시가배당률(%)', '배당성향(%)', '시가총액', '시가총액순위', '상장주식수',
       '액면가l매매단위', '외국인한도주식수(A)', '외국인보유주식수(B)', '외국인소진율(B/A)', '투자의견l목표주가',
       '52주최고l최저', 'PERlEPS(2023.12)', '추정PERlEPS', 'PBRlBPS (2023.12)',
       '배당수익률', '동일업종 PER', '동일업종 등락률', '배당수익률l2023.12', '배당수익률l2024.02',
       'PERlEPS(2024.02)', 'PBRlBPS (2024.02)', '배당수익률l2024.03',
       '배당수익률l2024.01', '배당수익률l2024.04'],
      dtype='object')

## 결측치

In [9]:
True + False + True

2

In [10]:
# 결측치의 합계를 구하기
raw.isnull().sum()

종목명                    0
현재가                    0
전일비                    0
등락률                    0
매수호가                   0
매도호가                   0
거래량                    0
거래대금                   0
전일거래량                  0
조회일자                   0
종목명_전처리                0
종목코드                   0
매출액                  138
영업이익                 138
당기순이익                140
영업이익률                138
순이익률                 140
ROE(지배주주)            164
부채비율                 164
당좌비율                 164
유보율                  164
EPS(원)               144
PER(배)               144
BPS(원)               164
PBR(배)               164
주당배당금(원)             164
시가배당률(%)             164
배당성향(%)              164
시가총액                   0
시가총액순위                 0
상장주식수                  0
액면가l매매단위               2
외국인한도주식수(A)            0
외국인보유주식수(B)            0
외국인소진율(B/A)            0
투자의견l목표주가              0
52주최고l최저               0
PERlEPS(2023.12)       1
추정PERlEPS              0
PBRlBPS (2023.12)      1
배당수익률                164
동일업종 PER               0
동일업종 등락률               0
배당수익률l2023.12         95
배당수익률l2024.02        163
PERlEPS(2024.02)     163
PBRlBPS (2024.02)    163
배당수익률l2024.03        163
배당수익률l2024.01        163
배당수익률l2024.04        161
dtype: int64

In [11]:
# 결측치의 비율 구하기
raw.isnull().mean() * 100

종목명                    0.000000
현재가                    0.000000
전일비                    0.000000
등락률                    0.000000
매수호가                   0.000000
매도호가                   0.000000
거래량                    0.000000
거래대금                   0.000000
전일거래량                  0.000000
조회일자                   0.000000
종목명_전처리                0.000000
종목코드                   0.000000
매출액                   84.146341
영업이익                  84.146341
당기순이익                 85.365854
영업이익률                 84.146341
순이익률                  85.365854
ROE(지배주주)            100.000000
부채비율                 100.000000
당좌비율                 100.000000
유보율                  100.000000
EPS(원)                87.804878
PER(배)                87.804878
BPS(원)               100.000000
PBR(배)               100.000000
주당배당금(원)             100.000000
시가배당률(%)             100.000000
배당성향(%)              100.000000
시가총액                   0.000000
시가총액순위                 0.000000
상장주식수                  0.000000
액면가l매매단위               1.219512
외국인한도주식수(A)            0.000000
외국인보유주식수(B)            0.000000
외국인소진율(B/A)            0.000000
투자의견l목표주가              0.000000
52주최고l최저               0.000000
PERlEPS(2023.12)       0.609756
추정PERlEPS              0.000000
PBRlBPS (2023.12)      0.609756
배당수익률                100.000000
동일업종 PER               0.000000
동일업종 등락률               0.000000
배당수익률l2023.12         57.926829
배당수익률l2024.02         99.390244
PERlEPS(2024.02)      99.390244
PBRlBPS (2024.02)     99.390244
배당수익률l2024.03         99.390244
배당수익률l2024.01         99.390244
배당수익률l2024.04         98.170732
dtype: float64

In [12]:
# 결측치 제거 전에 행과 열의 수 보기
raw.shape

(164, 50)

In [13]:
# 전체가 결측치인 컬럼은 삭제
df = raw.dropna(axis=1, how="all").copy()
df.shape

(164, 40)

In [15]:
# 삭제된 컬럼의 수를 계산
raw.shape[1] - df.shape[1]

10

In [16]:
# info를 통해 결측치 데이터 타입을 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 40 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   종목명                164 non-null    object
 1   현재가                164 non-null    float64
 2   전일비                164 non-null    object
 3   등락률                164 non-null    object
 4   매수호가               164 non-null    float64
 5   매도호가               164 non-null    float64
 6   거래량                164 non-null    float64
 7   거래대금               164 non-null    float64
 8   전일거래량              164 non-null    float64
 9   조회일자               164 non-null    object
 10  종목명_전처리            164 non-null    object
 11  종목코드               164 non-null    object
 12  매출액                26 non-null     float64
 13  영업이익               26 non-null     float64
 14  당기순이익              24 non-null     float64
 15  영업이익률              26 non-null     float64
 16  순이익률               24 non-null     float64
 17  EPS(원)             20 non-null     float64
 18  PER(배)             20 non-null     float64
 19  시가총액               164 non-null    object
 20  시가총액순위             164 non-null    object
 21  상장주식수              164 non-null    int64
 22  액면가l매매단위           162 non-null    object
 23  외국인한도주식수(A)        164 non-null    int64
 24  외국인보유주식수(B)        164 non-null    int64
 25  외국인소진율(B/A)        164 non-null    object
 26  투자의견l목표주가          164 non-null    object
 27  52주최고l최저           164 non-null    object
 28  PERlEPS(2023.12)   163 non-null    object
 29  추정PERlEPS          164 non-null    object
 30  PBRlBPS (2023.12)  163 non-null    object
 31  동일업종 PER           164 non-null    object
 32  동일업종 등락률           164 non-null    object
 33  배당수익률l2023.12      69 non-null     object
 34  배당수익률l2024.02      1 non-null      object
 35  PERlEPS(2024.02)   1 non-null      object
 36  PBRlBPS (2024.02)  1 non-null      object
 37  배당수익률l2024.03      1 non-null      object
 38  배당수익률l2024.01      1 non-null      object
 39  배당수익률l2024.04      3 non-null      object
dtypes: float64(13), int64(3), object(24)
memory usage: 51.4+ KB

## 파생변수 만들기와 텍스트 데이터 다루기
<img src="https://pandas.pydata.org/docs/_images/05_newcolumn_1.svg">

* 코스피/코스닥 구분 만들기
* 시가총액 순위 분리하기
* 액면가l매매단위
* 52주최고l최저

### 코스피/코스닥 컬럼 만들기

In [17]:
# "코스피/코스닥" 컬럼 만들기
#  * 는 코스닥 종목. str.endswith 를 사용
df.loc[df["종목명"].str.endswith("*"), "코스피/코스닥"] = "코스닥"
df.loc[~df["종목명"].str.endswith("*"), "코스피/코스닥"] = "코스피"

In [18]:
df["코스피/코스닥"].tail()

159    코스피
160    코스피
161    코스닥
162    코스닥
163    코스닥
Name: 코스피/코스닥, dtype: object

In [19]:
# "코스피/코스닥" 빈도수를 확인
df["코스피/코스닥"].value_counts()

코스닥    91
코스피    73
Name: 코스피/코스닥, dtype: int64

###  시가총액 수치형태로 만들기

In [20]:
# df['시가총액(억원)']
df["시가총액(억원)"] = df["시가총액"].str.replace("억원", "")
df["시가총액(억원)"] = df["시가총액(억원)"].str.replace("조|,", "")
df["시가총액(억원)"] = df["시가총액(억원)"].str.replace(" ", "")
df["시가총액(억원)"] = df["시가총액(억원)"].str.strip()
df["시가총액(억원)"] = df["시가총액(억원)"].astype(int)
df["시가총액(억원)"]

C:\Users\user\AppData\Local\Temp\ipykernel_17704\2060011027.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df["시가총액(억원)"] = df["시가총액(억원)"].str.replace("조|,", "")

0       492
1      1806
2      1086
3      1159
4      1932
       ...
159    1922
160    3796
161    1279
162    1666
163     572
Name: 시가총액(억원), Length: 164, dtype: int32

* [정규 표현식 - 위키백과, 우리 모두의 백과사전](https://ko.wikipedia.org/wiki/%EC%A0%95%EA%B7%9C_%ED%91%9C%ED%98%84%EC%8B%9D)

In [21]:
# 정규표현식을 사용한 숫자 추출

df["시가총액(억원)"] = df["시가총액"].str.replace("[^0-9]", "").astype(int)
df["시가총액(억원)"].head(1)

C:\Users\user\AppData\Local\Temp\ipykernel_17704\780582283.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df["시가총액(억원)"] = df["시가총액"].str.replace("[^0-9]", "").astype(int)

0    492
Name: 시가총액(억원), dtype: int32

### 시가총액 순위 수치데이터로 만들기

In [22]:
# '시가총액순위(전처리)' column에서도 '위'를 빼고 수치데이터로 변경
df["시가총액순위(전처리)"] =  df["시가총액순위"].str.split(" ", expand=True)[1]
df["시가총액순위(전처리)"] = df["시가총액순위(전처리)"].str.replace("위", "").astype(int)
df["시가총액순위(전처리)"]

0      1344
1       498
2       887
3       753
4       455
       ...
159     462
160     215
161     685
162     545
163    1242
Name: 시가총액순위(전처리), Length: 164, dtype: int32

In [23]:
# 숫자를 제외한 문자는 빈문자""로 변경
df["시가총액순위(전처리)"] = df["시가총액순위"].str.replace("[^0-9]", "").astype(int)

C:\Users\user\AppData\Local\Temp\ipykernel_17704\3549155899.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df["시가총액순위(전처리)"] = df["시가총액순위"].str.replace("[^0-9]", "").astype(int)

### 52주최고l최저

In [24]:
# '52주최고l최저' => 52주최고, 52주최저 두 개의  컬럼으로 나누어 전처리
df["52주최고"] = df["52주최고l최저"].str.split("  l  ", expand=True)[0]
df["52주최저"] = df["52주최고l최저"].str.split("  l  ", expand=True)[1]

In [25]:
# 일부 column들을 수치형 데이터로 바꿀수 있도록 ','와 같은 문자들을 없애고 새로운 column에 수치형 데이터로 입력
# 이런 수치형 데이터의 column들로 새로운 데이터 column들을 생성
df["52주최고"] = df["52주최고"].str.replace(",", "").astype(int)
df["52주최저"] = df["52주최저"].str.replace(",", "").astype(int)

In [26]:
# 52주차액: 52주최고 - 52주최저 
# 52주차액비율 : 52주최고 / 52주최저 
df["52주차액"] = df["52주최고"] - df["52주최저"]
df["52주차액비율"] = df["52주최고"] / df["52주최저"]

In [27]:
# 현재-최고가 : 현재가 - 52주최고
# 현재/최고가비율 : 현재가 / 52주최고
df["현재-최고가"] = df["현재가"] - df["52주최고"]
df["현재/최고가비율"] = df["현재가"] / df["52주최고"]

In [28]:
df[["종목명", "52주차액", "52주차액비율", "52주최고", "52주최저", "현재-최고가", "현재/최고가비율"]].head()

           종목명  52주차액   52주차액비율  52주최고  52주최저   현재-최고가  현재/최고가비율
0    한국유니온제약 *   2250  1.534442   6460   4210   -240.0  0.962848
1       에이비온 *   5010  2.063694   9720   4710  -1520.0  0.843621
2  에이프로젠바이오로직스   5460  4.721881   6927   1467  -5296.0  0.235455
3      광동헬스바이오   7370  1.972296  14950   7580 -12240.0  0.181271
4      대봉엘에스 *   1960  2.661017   3140   1180   7310.0  3.328025

### 투자의견l목표주가 astype과 to_numeric

In [29]:
type(np.nan)

float

In [30]:
# '투자의견l목표주가' => 투자의견, 매수매도, 목표주가 컬럼으로 나누어 전처리
# df["투자의견"]
# df["매수매도"]
# df["목표주가"]
df["목표주가"] = df["투자의견l목표주가"].str.split("  l  ", expand=True)[1]
df["목표주가"] = df["목표주가"].replace("N/A", np.nan).str.replace(",", "").astype(float)
df["목표주가"]

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
        ...
159        NaN
160    53333.0
161        NaN
162        NaN
163        NaN
Name: 목표주가, Length: 164, dtype: float64

In [31]:
df["투자의견"] = df["투자의견l목표주가"].str.split("  l  ", expand=True)[0]
df["투자의견"] = df["투자의견"].replace("N/A", np.nan)
df["매수매도"] = df["투자의견"].str.replace("[0-9.]", "")
df["투자의견"] = df["투자의견"].str.replace("[^0-9.]", "").astype(float)
df["투자의견"]

C:\Users\user\AppData\Local\Temp\ipykernel_17704\768070381.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df["매수매도"] = df["투자의견"].str.replace("[0-9.]", "")
C:\Users\user\AppData\Local\Temp\ipykernel_17704\768070381.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  df["투자의견"] = df["투자의견"].str.replace("[^0-9.]", "").astype(float)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
159    NaN
160    4.0
161    NaN
162    NaN
163    NaN
Name: 투자의견, Length: 164, dtype: float64

In [32]:
df["투자의견"].astype(float)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
159    NaN
160    4.0
161    NaN
162    NaN
163    NaN
Name: 투자의견, Length: 164, dtype: float64

In [33]:
# 투자의견의 수치만 pd.to_numeric 으로 숫자로 만들기
df["투자의견"] = pd.to_numeric(df["투자의견"])

In [34]:
# 투자의견 컬럼만 가져와서 describe로 기술통계 값 보기
df["투자의견"].describe()

count    34.000000
mean      3.970588
std       0.171499
min       3.000000
25%       4.000000
50%       4.000000
75%       4.000000
max       4.000000
Name: 투자의견, dtype: float64

### 데이터 타입 변경하기
* "동일업종 PER 컬럼"에서 "배" 문자를 제거하고 수치 변수로 변환해 주세요.
* 전처리 결괏값은 df["동일업종 PER(배)"]라는 컬럼에 담아주세요

In [35]:
# "동일업종 PER"
df["동일업종 PER"]

0      101.57배
1      101.57배
2      101.57배
3      101.57배
4      101.57배
        ...
159    101.57배
160    101.57배
161    101.57배
162    101.57배
163    101.57배
Name: 동일업종 PER, Length: 164, dtype: object

In [36]:
# "동일업종 PER 컬럼"에서 "배" 문자를 제거하고 수치 변수로 변환

df["동일업종 PER"] = df["동일업종 PER"].str.replace("배", "")

In [37]:
# str.replace, astype를 이용
df["동일업종 PER"] = df["동일업종 PER"].astype(float)
df["동일업종 PER"]

0      101.57
1      101.57
2      101.57
3      101.57
4      101.57
        ...
159    101.57
160    101.57
161    101.57
162    101.57
163    101.57
Name: 동일업종 PER, Length: 164, dtype: float64

## filter와 melt로 여러 컬럼 전처리하기

### PER와 EPS 

#### PER 주가수익비율

* "이 주식은 비싼가, 주식시장이 거품인가" 판단하는 시금석
* PER = 주식가격 / 주당순이익(EPS)

물건을 살 때 값을 얼마나 줘야 좋은 건지 판단할 기준은 수없이 많다. 내게 얼마나 절실한가. 이 물건이 얼마나 유용하고 값어치가 있나. 혹은 어느 정도나 오래 사용할 수 있나. 물건에 대한 다른 사람들의 평판은 어떤가. 물건이 내게 주는 수익은 어느 정도인가…. 생각해보면 쉽게 떠오르는 이런저런 이유들은 어려운 주식투자나, 투자결정에도 그대로 적용된다.

이런 점에서 흔히 투자자들 사이에서 `퍼(PER)`로 불리는 **주가수익비율(Price earning ratio, 이하 PER)**은 어떤 회사의 주식가치, 더 나아가 전체 주식시장의 가치가 고평가 됐는지 가늠할 수 있는 유용한 잣대다. **PER은 현재 시장에서 매매되는 특정회사의 주식가격을 주당순이익으로 나눈 값을 말한다.** 한 주에 만 원하는 회사주식이 1년에 주당 1000원의 순이익을 낸다면? PER은 10이 된다. 이 수치가 회사의 가치를 어떻게 반영한다는 얘기일까?

* 출처 [네이버 지식백과]주가수익비율(PER) - "이 주식은 비싼가, 주식시장이 거품인가" 판단하는 시금석 (금융사전, 김태근)
* https://terms.naver.com/entry.nhn?docId=3571127&cid=58781&categoryId=58781

#### EPS 주당순이익

* EPS =  순이익(당기순이익) / 그 기업이 발행한 총 주식수

주당순이익(EPS)은 기업이 벌어들인 순이익(당기순이익)을 그 기업이 발행한 총 주식수로 나눈 값으로, 1주당 이익을 얼마나 창출하였느냐를 나타내는 지표이다. 즉 해당 회사가 1년간 올린 수익에 대한 주주의 몫을 나타내는 지표라 할 수 있다. 또한 주당순이익은 주가수익비율(PER)계산의 기초가 되기도 한다.

EPS가 높을수록 주식의 투자 가치는 높다고 볼 수 있으며, 그만큼 해당 회사의 경영실적이 양호하다는 뜻이다. 따라서 배당 여력도 많으므로 주가에 긍정적인 영향을 미친다.

EPS는 당기순이익 규모가 늘면 높아지게 되고, 전환사채의 주식전환이나 증자로 주식수가 많아지면 낮아지게 된다. 특히 최근 주식시장의 패턴이 기업의 수익성을 중시하는 쪽으로 바뀌면서 EPS의 크기가 중요시되고 있다.

* 출처 : [네이버 지식백과] 주당순이익(EPS) (시사상식사전, pmg 지식엔진연구소)
* https://terms.naver.com/entry.nhn?docId=74510&cid=43667&categoryId=43667

### filter 를 사용해 특정 텍스트가 들어가는 컬럼 찾기
* [정규 표현식 - 위키백과, 우리 모두의 백과사전](https://ko.wikipedia.org/wiki/%EC%A0%95%EA%B7%9C_%ED%91%9C%ED%98%84%EC%8B%9D)

In [38]:
# df.filter(regex=)를 통해 "PERlEPS" 가 들어가는 컬럼 가져오기
# 특정 컬럼을 가져오고 종목코드를 추가
df_per_eps = df.filter(regex="^PERlEPS").copy()
df_per_eps["종목코드"] = df["종목코드"]
df_per_eps

      PERlEPS(2023.12) PERlEPS(2024.02)    종목코드
0      N/A  l  -2,297원              NaN  080720
1      N/A  l  -1,524원              NaN  203400
2      N/A  l  -1,838원              NaN  003060
3      27.72배  l  377원              NaN  086220
4        N/A  l  -540원              NaN  078140
..                 ...              ...     ...
159      N/A  l  -703원              NaN  003000
160  14.61배  l  2,314원              NaN  000640
161      N/A  l  -546원              NaN  397030
162      N/A  l  -110원              NaN  047920
163    N/A  l  -1,366원              NaN  359090

[164 rows x 3 columns]

### melt로 tidy data 만들기

<img src="https://pandas.pydata.org/docs/_images/reshaping_melt.png" width="600">

* https://pandas.pydata.org/docs/user_guide/reshaping.html#reshaping-by-melt
* [Tidy Data 란?](https://vita.had.co.nz/papers/tidy-data.pdf)

In [39]:
# melt를 통해 종목코드 녹여내기
df_per_eps_melt = df_per_eps.melt(id_vars="종목코드")
df_per_eps_melt

       종목코드          variable            value
0    080720  PERlEPS(2023.12)  N/A  l  -2,297원
1    203400  PERlEPS(2023.12)  N/A  l  -1,524원
2    003060  PERlEPS(2023.12)  N/A  l  -1,838원
3    086220  PERlEPS(2023.12)  27.72배  l  377원
4    078140  PERlEPS(2023.12)    N/A  l  -540원
..      ...               ...              ...
323  003000  PERlEPS(2024.02)              NaN
324  000640  PERlEPS(2024.02)              NaN
325  397030  PERlEPS(2024.02)              NaN
326  047920  PERlEPS(2024.02)              NaN
327  359090  PERlEPS(2024.02)              NaN

[328 rows x 3 columns]

In [40]:
# 종목코드별로 value_counts를 통해  PERlEPS 행이 몇 개인지 보기
df_per_eps_melt["종목코드"].value_counts()

080720    2
115180    2
066700    2
299170    2
009290    2
         ..
217950    2
000105    2
200780    2
002720    2
359090    2
Name: 종목코드, Length: 164, dtype: int64

### 결측치 데이터 제거
<img src="https://pandas.pydata.org/docs/_images/03_subset_rows.svg">

In [41]:
# PERlEPS 데이터프레임에서 결측치 데이터 제거

df_pe = df_per_eps_melt.dropna()
df_pe

       종목코드          variable              value
0    080720  PERlEPS(2023.12)    N/A  l  -2,297원
1    203400  PERlEPS(2023.12)    N/A  l  -1,524원
2    003060  PERlEPS(2023.12)    N/A  l  -1,838원
3    086220  PERlEPS(2023.12)    27.72배  l  377원
4    078140  PERlEPS(2023.12)      N/A  l  -540원
..      ...               ...                ...
160  000640  PERlEPS(2023.12)  14.61배  l  2,314원
161  397030  PERlEPS(2023.12)      N/A  l  -546원
162  047920  PERlEPS(2023.12)      N/A  l  -110원
163  359090  PERlEPS(2023.12)    N/A  l  -1,366원
267  115180  PERlEPS(2024.02)    25.34배  l  149원

[164 rows x 3 columns]

In [42]:
# variable 컬럼명을 rename을 통해 "PERlEPS"로 변경
df_pe = df_pe.rename(columns={"variable": "PERlEPS"})
df_pe

       종목코드           PERlEPS              value
0    080720  PERlEPS(2023.12)    N/A  l  -2,297원
1    203400  PERlEPS(2023.12)    N/A  l  -1,524원
2    003060  PERlEPS(2023.12)    N/A  l  -1,838원
3    086220  PERlEPS(2023.12)    27.72배  l  377원
4    078140  PERlEPS(2023.12)      N/A  l  -540원
..      ...               ...                ...
160  000640  PERlEPS(2023.12)  14.61배  l  2,314원
161  397030  PERlEPS(2023.12)      N/A  l  -546원
162  047920  PERlEPS(2023.12)      N/A  l  -110원
163  359090  PERlEPS(2023.12)    N/A  l  -1,366원
267  115180  PERlEPS(2024.02)    25.34배  l  149원

[164 rows x 3 columns]

In [43]:
# df_pe에서 PER, EPS 컬럼을 따로 생성
df_pe["PER"] = df_pe["value"].str.split("  l  ", expand=True)[0]
df_pe["EPS"] = df_pe["value"].str.split("  l  ", expand=True)[1]

In [44]:
# PER, EPS 컬럼의 N/A 값을 결측치로 만들기
df_pe["PER"] = df_pe["PER"].replace("N/A", np.nan)
df_pe["EPS"] = df_pe["EPS"].replace("N/A", np.nan)

In [45]:
#  PER, EPS 값 중 둘 다 결측치는 notnull 혹은 isnull을 사용해 제거
df_pe = df_pe[df_pe["PER"].notnull() | df_pe["EPS"].notnull()].copy()

In [46]:
# PER(배) 컬럼을 만들고 수치데이터 형태로 변환
df_pe["PER(배)"] = df_pe["PER"].str.replace("[^0-9.]", "").astype(float)

C:\Users\user\AppData\Local\Temp\ipykernel_17704\1097900316.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df_pe["PER(배)"] = df_pe["PER"].str.replace("[^0-9.]", "").astype(float)

In [47]:
# EPS(원) 컬럼을 만들고 수치데이터 형태로 변환
df_pe["EPS(원)"] = df_pe["EPS"].str.replace("원|,", "").astype(int)

C:\Users\user\AppData\Local\Temp\ipykernel_17704\4272125509.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df_pe["EPS(원)"] = df_pe["EPS"].str.replace("원|,", "").astype(int)

In [48]:
# 필요한 컬럼만 따로 가져오기
df_pe = df_pe[["종목코드", "PERlEPS", "PER(배)", "EPS(원)"]].copy()
df_pe

       종목코드           PERlEPS  PER(배)  EPS(원)
0    080720  PERlEPS(2023.12)     NaN   -2297
1    203400  PERlEPS(2023.12)     NaN   -1524
2    003060  PERlEPS(2023.12)     NaN   -1838
3    086220  PERlEPS(2023.12)   27.72     377
4    078140  PERlEPS(2023.12)     NaN    -540
..      ...               ...     ...     ...
160  000640  PERlEPS(2023.12)   14.61    2314
161  397030  PERlEPS(2023.12)     NaN    -546
162  047920  PERlEPS(2023.12)     NaN    -110
163  359090  PERlEPS(2023.12)     NaN   -1366
267  115180  PERlEPS(2024.02)   25.34     149

[164 rows x 4 columns]

### 중복 데이터 확인

In [49]:
# "종목코드"기준으로 중복된 데이터 찾기
df_pe[df_pe.duplicated("종목코드")]

Empty DataFrame
Columns: [종목코드, PERlEPS, PER(배), EPS(원)]
Index: []

In [50]:
# 만약 중복데이터가 있다면 다음과 같은 방법으로 제거
# 추출했던 원래 데이터프레임 df와 다시 merge 로 합치기 위해 
# drop_duplicates 를 사용해 종목코드가 중복되는 행은 제거
# "종목코드", "PERlEPS" 로 정렬,
# drop_duplicates 로 제거시 keep="first" 로 위에 있는 데이터를 남김
df_pe = df_pe.sort_values(["종목코드", "PERlEPS"])
df_pe = df_pe.drop_duplicates(["종목코드", "PERlEPS"])
df_pe

       종목코드           PERlEPS  PER(배)  EPS(원)
111  000020  PERlEPS(2023.12)     NaN    -766
69   000100  PERlEPS(2023.12)   42.34     529
56   000105  PERlEPS(2023.12)     NaN    -130
44   000220  PERlEPS(2023.12)     NaN   -2279
51   000225  PERlEPS(2023.12)   20.95     296
..      ...               ...     ...     ...
161  397030  PERlEPS(2023.12)     NaN    -546
89   446600  PERlEPS(2023.12)   40.76     132
90   900120  PERlEPS(2023.12)     NaN   -2092
122  950210  PERlEPS(2023.12)  506.72      67
5    950220  PERlEPS(2023.12)   10.43     944

[164 rows x 4 columns]

In [51]:
# 종목코드값 기준으로 중복데이터를 확인
df_pe["종목코드"].value_counts().unique()

array([1], dtype=int64)

### PBRlBPS 전처리


#### PBR(주가순자산비율, price-to-book ratio, P/B ratio)

* PBR = 주가/BPS(주당순자산가치)
* 주가는 그 회사의 종합적인 평가이므로 주주 소유분을 초과한 부분은 모두 그 회사의 잠재적인 프리미엄이 되기 때문에 **경영의 종합력이 뛰어나면 뛰어날수록 배율이 높아진다**고 할 수 있다. 일반적으로 이 지표는 PER과 함께 사용되는데, 이는 주가순자산배율이 그 회사를 정적인 상태 즉 스토크(stock)면에서 보고 있는데 반하여 주가수익률은 동적인 상태 즉 플로(flow)면에서 보고 있으므로 두 가지 지표가 서로 보완관계에 있다.

* 다만 이 주가 순자산배율에도 **주주소유분이 장부가격에 의해 계산되고 있어 반드시 정확하다고 할 수 없고 또 그 계산기준이 전기의 결산기가 된다는 등의 난점이 있다.**
* 출처 : [주가순자산비율 - 위키백과, 우리 모두의 백과사전](https://ko.wikipedia.org/wiki/%EC%A3%BC%EA%B0%80%EC%88%9C%EC%9E%90%EC%82%B0%EB%B9%84%EC%9C%A8)

#### BPS(주당순자산가치, Book-value Per Share)

* 주당순자산가치 = 기업의 순자산/ 발행 주식수
* 주당순자산가치는, '청산가치' 라고도 불린다. 그 이유는 현재 시점에서 기업의 활동을 중단시키고 그 부를 모든 주주들에게 나눠줄 경우 한주당 얼마씩이 돌아가는가를 나타내는 수치이기 때문이다. 보통 주당순자산가치라는 말은 잘 쓰지 않고 BPS라고 하므로 이하 BPS로 쓴다.

* BPS가 높다는 것은 자기자본의 비중이 크거나 회사 가치가 높다는 것을 나타낸다. BPS에는 주가 정보가 고려되어 있지 않으므로, 이 회사의 주가가 자산 가치에 비해 얼마나 저평가 혹은 고평가되어 있는지 판단하기 위해 PBR이라는 값을 사용한다.

* PBR 값은 BPS 값으로 현재 주가를 나눈 것이다. BPS가 1만원인 위 사례에서 주가가 5,000원이라면 PBR은 0.5가 되고, 주가가 20,000원이라면 PBR은 2가 된다. 즉 전자의 경우 주가는 실제의 자산에 비해 저평가되어 되어 있는 것이고, 후자의 경우 주가는 실제 자산에 비해 고평가 되어 있는 것이다.

* 출처 : [주당순자산가치 - 위키백과, 우리 모두의 백과사전](https://ko.wikipedia.org/wiki/%EC%A3%BC%EB%8B%B9%EC%88%9C%EC%9E%90%EC%82%B0%EA%B0%80%EC%B9%98)

In [52]:
# filter를 사용해 PBRlBPS 컬럼 가져오기
# 종목코드 추가
df_pbr_bps = df.filter(regex="PBRlBPS").copy()
df_pbr_bps["종목코드"] = df["종목코드"]
df_pbr_bps

     PBRlBPS (2023.12) PBRlBPS (2024.02)    종목코드
0     1.48배  l  4,196원               NaN  080720
1      18.10배  l  453원               NaN  203400
2     0.29배  l  5,607원               NaN  003060
3    0.95배  l  11,027원               NaN  086220
4       2.58배  l  757원               NaN  078140
..                 ...               ...     ...
159   2.98배  l  2,497원               NaN  003000
160  1.77배  l  19,055원               NaN  000640
161    10.88배  l  421원               NaN  397030
162   0.86배  l  2,273원               NaN  047920
163   2.79배  l  1,001원               NaN  359090

[164 rows x 3 columns]

In [53]:
# melt로 tidy data 만들기
df_pbr_bps_melt = df_pbr_bps.melt(id_vars="종목코드").copy()
df_pbr_bps_melt

       종목코드           variable              value
0    080720  PBRlBPS (2023.12)   1.48배  l  4,196원
1    203400  PBRlBPS (2023.12)    18.10배  l  453원
2    003060  PBRlBPS (2023.12)   0.29배  l  5,607원
3    086220  PBRlBPS (2023.12)  0.95배  l  11,027원
4    078140  PBRlBPS (2023.12)     2.58배  l  757원
..      ...                ...                ...
323  003000  PBRlBPS (2024.02)                NaN
324  000640  PBRlBPS (2024.02)                NaN
325  397030  PBRlBPS (2024.02)                NaN
326  047920  PBRlBPS (2024.02)                NaN
327  359090  PBRlBPS (2024.02)                NaN

[328 rows x 3 columns]

In [54]:
# 결측치 제거
df_pb = df_pbr_bps_melt.dropna()
df_pb

       종목코드           variable              value
0    080720  PBRlBPS (2023.12)   1.48배  l  4,196원
1    203400  PBRlBPS (2023.12)    18.10배  l  453원
2    003060  PBRlBPS (2023.12)   0.29배  l  5,607원
3    086220  PBRlBPS (2023.12)  0.95배  l  11,027원
4    078140  PBRlBPS (2023.12)     2.58배  l  757원
..      ...                ...                ...
160  000640  PBRlBPS (2023.12)  1.77배  l  19,055원
161  397030  PBRlBPS (2023.12)    10.88배  l  421원
162  047920  PBRlBPS (2023.12)   0.86배  l  2,273원
163  359090  PBRlBPS (2023.12)   2.79배  l  1,001원
267  115180  PBRlBPS (2024.02)   1.19배  l  3,182원

[164 rows x 3 columns]

In [55]:
# variable 컬럼명을 "PBRlBPS"로 변경
df_pb = df_pb.rename(columns={"variable":"PBRlBPS"})
df_pb

       종목코드            PBRlBPS              value
0    080720  PBRlBPS (2023.12)   1.48배  l  4,196원
1    203400  PBRlBPS (2023.12)    18.10배  l  453원
2    003060  PBRlBPS (2023.12)   0.29배  l  5,607원
3    086220  PBRlBPS (2023.12)  0.95배  l  11,027원
4    078140  PBRlBPS (2023.12)     2.58배  l  757원
..      ...                ...                ...
160  000640  PBRlBPS (2023.12)  1.77배  l  19,055원
161  397030  PBRlBPS (2023.12)    10.88배  l  421원
162  047920  PBRlBPS (2023.12)   0.86배  l  2,273원
163  359090  PBRlBPS (2023.12)   2.79배  l  1,001원
267  115180  PBRlBPS (2024.02)   1.19배  l  3,182원

[164 rows x 3 columns]

In [56]:
# PBR, BPS 컬럼을 만들기
df_pb["PBR"] = df_pb["value"].str.split("  l  ", expand=True)[0]
df_pb["BPS"] = df_pb["value"].str.split("  l  ", expand=True)[1]

In [57]:
# N/A 값(문자) np.nan(결측치)로 변환
df_pb["PBR"] = df_pb["PBR"].replace("N/A", np.nan)
df_pb["BPS"] = df_pb["BPS"].replace("N/A", np.nan)

In [58]:
# PBR(배), BPS(원) 컬럼을 만들기
df_pb["PBR(배)"] = df_pb["PBR"].str.replace("배", "").astype(float)
df_pb["BPS(원)"] = df_pb["BPS"].str.replace("원|,", "").astype(float)

C:\Users\user\AppData\Local\Temp\ipykernel_17704\3602030462.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  df_pb["BPS(원)"] = df_pb["BPS"].str.replace("원|,", "").astype(float)

In [59]:
# 종목코드 기준 value_counts 를 구해 중복값이 있는지 확인
df_pb["종목코드"].value_counts().unique()

array([1], dtype=int64)

In [60]:
# "종목코드","PBRlBPS" 로 중복값이 있는지 확인
df_pb[df_pb.duplicated(["종목코드"])]

Empty DataFrame
Columns: [종목코드, PBRlBPS, value, PBR, BPS, PBR(배), BPS(원)]
Index: []

In [61]:
df_pb = df_pb[["종목코드", "PBRlBPS", "PBR(배)", "BPS(원)"]].copy()
df_pb

       종목코드            PBRlBPS  PBR(배)   BPS(원)
0    080720  PBRlBPS (2023.12)    1.48   4196.0
1    203400  PBRlBPS (2023.12)   18.10    453.0
2    003060  PBRlBPS (2023.12)    0.29   5607.0
3    086220  PBRlBPS (2023.12)    0.95  11027.0
4    078140  PBRlBPS (2023.12)    2.58    757.0
..      ...                ...     ...      ...
160  000640  PBRlBPS (2023.12)    1.77  19055.0
161  397030  PBRlBPS (2023.12)   10.88    421.0
162  047920  PBRlBPS (2023.12)    0.86   2273.0
163  359090  PBRlBPS (2023.12)    2.79   1001.0
267  115180  PBRlBPS (2024.02)    1.19   3182.0

[164 rows x 4 columns]

### 배당 수익률 전처리

In [62]:
# PER|EPS 전처리와 마찬가리로 배당수익률 데이터를 전처리
# df.filter(regex=) 로 배당수익률이 들어가는 컬럼만 찾고 종목코드 추가
df_income = df.filter(regex="배당수익률").copy()

In [63]:
# 추후 병합을 위해 데이터프레임에 종목코드를 추가
df_income["종목코드"] = df["종목코드"]
df_income

,배당수익률l2023.12,배당수익률l2024.02,배당수익률l2024.03,배당수익률l2024.01,배당수익률l2024.04,종목코드
0,NaN,NaN,NaN,NaN,NaN,080720
1,NaN,NaN,NaN,NaN,NaN,203400
2,NaN,NaN,NaN,NaN,NaN,003060
3,0.48%,NaN,NaN,NaN,NaN,086220
4,NaN,NaN,NaN,NaN,NaN,078140
...,...,...,...,...,...,...
159,NaN,NaN,NaN,NaN,NaN,003000
160,NaN,NaN,NaN,NaN,1.55%,000640
161,NaN,NaN,NaN,NaN,NaN,397030
162,NaN,NaN,NaN,NaN,NaN,047920
163,NaN,NaN,NaN,NaN,NaN,359090

In [64]:
# melt 로 여러 컬럼의 종목코드를 행으로 녹이고 결측치를 dropna 로 제거
df_in = df_income.melt(id_vars="종목코드").copy()
df_in = df_in.dropna()
df_in

       종목코드       variable  value
3    086220  배당수익률l2023.12  0.48%
5    950220  배당수익률l2023.12  3.55%
6    044820  배당수익률l2023.12  1.90%
8    007460  배당수익률l2023.12  1.03%
15   270870  배당수익률l2023.12  0.26%
..      ...            ...    ...
431  115180  배당수익률l2024.03  0.93%
606  004310  배당수익률l2024.01  3.85%
796  142760  배당수익률l2024.04  2.42%
811  003850  배당수익률l2024.04  1.86%
816  000640  배당수익률l2024.04  1.55%

[75 rows x 3 columns]

In [65]:
# 컬럼명을 "종목코드", "배당수익률기간", "배당수익률" 로 변경
df_in.columns = ["종목코드", "배당수익률기간", "배당수익률"]
df_in

       종목코드        배당수익률기간  배당수익률
3    086220  배당수익률l2023.12  0.48%
5    950220  배당수익률l2023.12  3.55%
6    044820  배당수익률l2023.12  1.90%
8    007460  배당수익률l2023.12  1.03%
15   270870  배당수익률l2023.12  0.26%
..      ...            ...    ...
431  115180  배당수익률l2024.03  0.93%
606  004310  배당수익률l2024.01  3.85%
796  142760  배당수익률l2024.04  2.42%
811  003850  배당수익률l2024.04  1.86%
816  000640  배당수익률l2024.04  1.55%

[75 rows x 3 columns]

In [66]:
# 배당수익률% 컬럼을 만들어 전처리

df_in["배당수익률%"] = df_in["배당수익률"].str.replace("%", "").astype(float)

In [67]:
# 종목코드가 종목당 2개 이상 있는 값이 있는지 확인
df_in["종목코드"].value_counts().unique()

array([1], dtype=int64)

In [68]:
# 전처리가 끝난 배당수익률 컬럼은 제거
del df_in["배당수익률"]

## merge 로 기존 데이터와 병합하기

<img src="https://pandas.pydata.org/docs/_images/08_merge_left.svg">

* concat과 merge의 차이
    * concat :  
        * axis=0 행을 기준으로 위아래로 **같은 컬럼끼리** 값을 이어 붙여 **새로운 행을 만듦**
        * axis=1 컬럼을 기준으로 **인덱스가 같은 값**을 옆으로 붙여 **새로운 컬럼을 만듦**
    * merge :
        * index 혹은 특정 컬럼 값을 기준으로 두 개의 데이터프레임을 연결
        
<img src="https://www.dofactory.com/img/sql/sql-joins.png">

* 이미지 출처 : https://www.dofactory.com/sql/join

In [70]:
df.shape

(164, 52)

In [72]:
# merge로 병합
# df와 df_pe를 병합니다. merge 전후 행과 열의 수를 확인해서 제대로 병합이 되었는지 확인하고 df_merge_pe 에 할당
df_merge_pe = df.merge(df_pe, left_on="종목코드", right_on="종목코드", how="left")
df_merge_pe.head(1)

,종목명,현재가,전일비,등락률,매수호가,매도호가,거래량,거래대금,전일거래량,조회일자,종목명_전처리,종목코드,매출액,영업이익,당기순이익,영업이익률,순이익률,EPS(원)_x,PER(배)_x,시가총액,시가총액순위,상장주식수,액면가l매매단위,외국인한도주식수(A),외국인보유주식수(B),외국인소진율(B/A),투자의견l목표주가,52주최고l최저,PERlEPS(2023.12),추정PERlEPS,PBRlBPS (2023.12),동일업종 PER,동일업종 등락률,배당수익률l2023.12,배당수익률l2024.02,PERlEPS(2024.02),PBRlBPS (2024.02),배당수익률l2024.03,배당수익률l2024.01,배당수익률l2024.04,코스피/코스닥,시가총액(억원),시가총액순위(전처리),52주최고,52주최저,52주차액,52주차액비율,현재-최고가,현재/최고가비율,목표주가,투자의견,매수매도,PERlEPS,PER(배)_y,EPS(원)_y
0,한국유니온제약 *,6220.0,상승 410,+7.06%,6220.0,6230.0,30120.0,184.0,7041.0,2024-05-12,한국유니온제약,080720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,492 억원,코스닥 1344위,7909829,500원 l 1주,7909829,53729,0.68%,N/A l N/A,"6,460 l 4,210","N/A l -2,297원",N/A l N/A,"1.48배 l 4,196원",101.57,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,코스닥,492,1344,6460,4210,2250,1.534442,-240.0,0.962848,NaN,NaN,NaN,PERlEPS(2023.12),NaN,-2297

In [73]:
df_merge_pe.shape

(164, 55)

In [74]:
# 위에서 병합한 데이터(df_merge_pe)에 PBRlBPS(df_pb) 데이터도 병합
df_merge_pb = df_merge_pe.merge(df_pb, on="종목코드", how="left")
df_merge_pb.head(1)

,종목명,현재가,전일비,등락률,매수호가,매도호가,거래량,거래대금,전일거래량,조회일자,종목명_전처리,종목코드,매출액,영업이익,당기순이익,영업이익률,순이익률,EPS(원)_x,PER(배)_x,시가총액,시가총액순위,상장주식수,액면가l매매단위,외국인한도주식수(A),외국인보유주식수(B),외국인소진율(B/A),투자의견l목표주가,52주최고l최저,PERlEPS(2023.12),추정PERlEPS,PBRlBPS (2023.12),동일업종 PER,동일업종 등락률,배당수익률l2023.12,배당수익률l2024.02,PERlEPS(2024.02),PBRlBPS (2024.02),배당수익률l2024.03,배당수익률l2024.01,배당수익률l2024.04,코스피/코스닥,시가총액(억원),시가총액순위(전처리),52주최고,52주최저,52주차액,52주차액비율,현재-최고가,현재/최고가비율,목표주가,투자의견,매수매도,PERlEPS,PER(배)_y,EPS(원)_y,PBRlBPS,PBR(배),BPS(원)
0,한국유니온제약 *,6220.0,상승 410,+7.06%,6220.0,6230.0,30120.0,184.0,7041.0,2024-05-12,한국유니온제약,080720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,492 억원,코스닥 1344위,7909829,500원 l 1주,7909829,53729,0.68%,N/A l N/A,"6,460 l 4,210","N/A l -2,297원",N/A l N/A,"1.48배 l 4,196원",101.57,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,코스닥,492,1344,6460,4210,2250,1.534442,-240.0,0.962848,NaN,NaN,NaN,PERlEPS(2023.12),NaN,-2297,PBRlBPS (2023.12),1.48,4196.0

In [75]:
df_merge_pb.shape

(164, 58)

In [77]:
# 위에서 병합한 데이터(df_merge_pb)에 배당수익률(df_in) 데이터도 병합
# df_final 이라는 변수에 담기
df_final = df_merge_pb.merge(df_in, how="left")

In [78]:
df_final.shape

(164, 60)

In [79]:
df_final.head()

,종목명,현재가,전일비,등락률,매수호가,매도호가,거래량,거래대금,전일거래량,조회일자,종목명_전처리,종목코드,매출액,영업이익,당기순이익,영업이익률,순이익률,EPS(원)_x,PER(배)_x,시가총액,시가총액순위,상장주식수,액면가l매매단위,외국인한도주식수(A),외국인보유주식수(B),외국인소진율(B/A),투자의견l목표주가,52주최고l최저,PERlEPS(2023.12),추정PERlEPS,PBRlBPS (2023.12),동일업종 PER,동일업종 등락률,배당수익률l2023.12,배당수익률l2024.02,PERlEPS(2024.02),PBRlBPS (2024.02),배당수익률l2024.03,배당수익률l2024.01,배당수익률l2024.04,코스피/코스닥,시가총액(억원),시가총액순위(전처리),52주최고,52주최저,52주차액,52주차액비율,현재-최고가,현재/최고가비율,목표주가,투자의견,매수매도,PERlEPS,PER(배)_y,EPS(원)_y,PBRlBPS,PBR(배),BPS(원),배당수익률기간,배당수익률%
0,한국유니온제약 *,6220.0,상승 410,+7.06%,6220.0,6230.0,30120.0,184.0,7041.0,2024-05-12,한국유니온제약,080720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,492 억원,코스닥 1344위,7909829,500원 l 1주,7909829,53729,0.68%,N/A l N/A,"6,460 l 4,210","N/A l -2,297원",N/A l N/A,"1.48배 l 4,196원",101.57,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,코스닥,492,1344,6460,4210,2250,1.534442,-240.0,0.962848,NaN,NaN,NaN,PERlEPS(2023.12),NaN,-2297,PBRlBPS (2023.12),1.48,4196.0,NaN,NaN
1,에이비온 *,8200.0,상승 490,+6.36%,8190.0,8200.0,240152.0,1946.0,171467.0,2024-05-12,에이비온,203400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,806 억원",코스닥 498위,22025993,500원 l 1주,22025993,68933,0.31%,N/A l N/A,"9,720 l 4,710","N/A l -1,524원",N/A l N/A,18.10배 l 453원,101.57,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,코스닥,1806,498,9720,4710,5010,2.063694,-1520.0,0.843621,NaN,NaN,NaN,PERlEPS(2023.12),NaN,-1524,PBRlBPS (2023.12),18.10,453.0,NaN,NaN
2,에이프로젠바이오로직스,1631.0,상승 90,+5.84%,1631.0,1632.0,498832.0,802.0,155279.0,2024-05-12,에이프로젠바이오로직스,003060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,086 억원",코스피 887위,66575468,500원 l 1주,66575468,374036,0.56%,N/A l N/A,"6,927 l 1,467","N/A l -1,838원",N/A l N/A,"0.29배 l 5,607원",101.57,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,코스피,1086,887,6927,1467,5460,4.721881,-5296.0,0.235455,NaN,NaN,NaN,PERlEPS(2023.12),NaN,-1838,PBRlBPS (2023.12),0.29,5607.0,NaN,NaN
3,광동헬스바이오,2710.0,상승 105,+4.03%,2610.0,2675.0,2.0,5.0,891.0,2024-05-12,광동헬스바이오,086220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,159 억원",코스닥 753위,11086579,500원 l 1주,11086579,203906,1.84%,N/A l N/A,"14,950 l 7,580",27.72배 l 377원,N/A l N/A,"0.95배 l 11,027원",101.57,+0.31%,0.48%,NaN,NaN,NaN,NaN,NaN,NaN,코스피,1159,753,14950,7580,7370,1.972296,-12240.0,0.181271,NaN,NaN,NaN,PERlEPS(2023.12),27.72,377,PBRlBPS (2023.12),0.95,11027.0,배당수익률l2023.12,0.48
4,대봉엘에스 *,10450.0,상승 400,+3.98%,10440.0,10450.0,203025.0,2095.0,84220.0,2024-05-12,대봉엘에스,078140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,932 억원",코스닥 455위,98867465,NaN,98867465,1221029,1.24%,N/A l N/A,"3,140 l 1,180",N/A l -540원,N/A l N/A,2.58배 l 757원,101.57,+0.31%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,코스닥,1932,455,3140,1180,1960,2.661017,7310.0,3.328025,NaN,NaN,NaN,PERlEPS(2023.12),NaN,-540,PBRlBPS (2023.12),2.58,757.0,NaN,NaN

## 사용하지 않는 컬럼 제거하기 drop

In [80]:
# l 구분자가 들어가는 컬럼명만 찾기
del_cols = df_final.filter(regex="l").columns
del_cols

Index(['액면가l매매단위', '투자의견l목표주가', '52주최고l최저', 'PERlEPS(2023.12)', '추정PERlEPS',
       'PBRlBPS (2023.12)', '배당수익률l2023.12', '배당수익률l2024.02',
       'PERlEPS(2024.02)', 'PBRlBPS (2024.02)', '배당수익률l2024.03',
       '배당수익률l2024.01', '배당수익률l2024.04', 'PERlEPS', 'PBRlBPS'],
      dtype='object')

In [81]:
# 위에서 찾은 컬럼명을 drop으로 삭제
df_final = df_final.drop(del_cols, axis=1).copy()

In [82]:
# 결측치수가 많거나 중복된 컬럼이 있는지 확인
df_final.shape

(164, 45)

In [83]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 164 entries, 0 to 163
Data columns (total 45 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   종목명          164 non-null    object
 1   현재가          164 non-null    float64
 2   전일비          164 non-null    object
 3   등락률          164 non-null    object
 4   매수호가         164 non-null    float64
 5   매도호가         164 non-null    float64
 6   거래량          164 non-null    float64
 7   거래대금         164 non-null    float64
 8   전일거래량        164 non-null    float64
 9   조회일자         164 non-null    object
 10  종목명_전처리      164 non-null    object
 11  종목코드         164 non-null    object
 12  매출액          26 non-null     float64
 13  영업이익         26 non-null     float64
 14  당기순이익        24 non-null     float64
 15  영업이익률        26 non-null     float64
 16  순이익률         24 non-null     float64
 17  EPS(원)_x     20 non-null     float64
 18  PER(배)_x     20 non-null     float64
 19  시가총액         164 non-null    object
 20  시가총액순위       164 non-null    object
 21  상장주식수        164 non-null    int64
 22  외국인한도주식수(A)  164 non-null    int64
 23  외국인보유주식수(B)  164 non-null    int64
 24  외국인소진율(B/A)  164 non-null    object
 25  동일업종 PER     164 non-null    float64
 26  동일업종 등락률     164 non-null    object
 27  코스피/코스닥      164 non-null    object
 28  시가총액(억원)     164 non-null    int32
 29  시가총액순위(전처리)  164 non-null    int32
 30  52주최고        164 non-null    int32
 31  52주최저        164 non-null    int32
 32  52주차액        164 non-null    int32
 33  52주차액비율      164 non-null    float64
 34  현재-최고가       164 non-null    float64
 35  현재/최고가비율     164 non-null    float64
 36  목표주가         34 non-null     float64
 37  투자의견         34 non-null     float64
 38  매수매도         34 non-null     object
 39  PER(배)_y     86 non-null     float64
 40  EPS(원)_y     164 non-null    int32
 41  PBR(배)       164 non-null    float64
 42  BPS(원)       164 non-null    float64
 43  배당수익률기간      75 non-null     object
 44  배당수익률%       75 non-null     float64
dtypes: float64(23), int32(6), int64(3), object(13)
memory usage: 55.1+ KB

In [84]:
# 전처리한 컬럼은 원본 컬럼을 제거
del_cols2 = ['종목명_전처리', '시가총액', '시가총액순위', '배당수익률기간']

In [85]:
# del_cols2 를 제거
df_final = df_final.drop(del_cols2, axis=1)

In [86]:
# 컬럼명 중 필요없는 컬럼이 없는지 확인
df_final.columns

Index(['종목명', '현재가', '전일비', '등락률', '매수호가', '매도호가', '거래량', '거래대금', '전일거래량',
       '조회일자', '종목코드', '매출액', '영업이익', '당기순이익', '영업이익률', '순이익률', 'EPS(원)_x',
       'PER(배)_x', '상장주식수', '외국인한도주식수(A)', '외국인보유주식수(B)', '외국인소진율(B/A)',
       '동일업종 PER', '동일업종 등락률', '코스피/코스닥', '시가총액(억원)', '시가총액순위(전처리)', '52주최고',
       '52주최저', '52주차액', '52주차액비율', '현재-최고가', '현재/최고가비율', '목표주가', '투자의견',
       '매수매도', 'PER(배)_y', 'EPS(원)_y', 'PBR(배)', 'BPS(원)', '배당수익률%'],
      dtype='object')

In [87]:
df_final.shape

(164, 41)

## CSV 파일로 저장하기

In [88]:
# 기존 파일명을 변경해서 새로 저장할 파일명을 만듭니다.
file_name

'upjong_no_261_2024-05-12.csv'

In [89]:
# 저장할 파일명을 만들기
# 기존 파일명에 _ver2 를 붙이기
final_file_name = file_name.replace(".csv", "_ver2.csv")
final_file_name

'upjong_no_261_2024-05-12_ver2.csv'

In [90]:
# final_file_name 변수에 있는 파일명으로 저장
df_final.to_csv(final_file_name, index=False)

In [91]:
# final_file_name 변수에 있는 값을 읽어오기
# 이 때, 종목코드는 dtype={"종목코드":np.object} 로 불러오기
pd.read_csv(final_file_name, dtype={"종목코드":np.object})

C:\Users\user\AppData\Local\Temp\ipykernel_17704\198865216.py:3: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  pd.read_csv(final_file_name, dtype={"종목코드":np.object})

,종목명,현재가,전일비,등락률,매수호가,매도호가,거래량,거래대금,전일거래량,조회일자,종목코드,매출액,영업이익,당기순이익,영업이익률,순이익률,EPS(원)_x,PER(배)_x,상장주식수,외국인한도주식수(A),외국인보유주식수(B),외국인소진율(B/A),동일업종 PER,동일업종 등락률,코스피/코스닥,시가총액(억원),시가총액순위(전처리),52주최고,52주최저,52주차액,52주차액비율,현재-최고가,현재/최고가비율,목표주가,투자의견,매수매도,PER(배)_y,EPS(원)_y,PBR(배),BPS(원),배당수익률%
0,한국유니온제약 *,6220.0,상승 410,+7.06%,6220.0,6230.0,30120.0,184.0,7041.0,2024-05-12,080720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7909829,7909829,53729,0.68%,101.57,+0.31%,코스닥,492,1344,6460,4210,2250,1.534442,-240.0,0.962848,NaN,NaN,NaN,NaN,-2297,1.48,4196.0,NaN
1,에이비온 *,8200.0,상승 490,+6.36%,8190.0,8200.0,240152.0,1946.0,171467.0,2024-05-12,203400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22025993,22025993,68933,0.31%,101.57,+0.31%,코스닥,1806,498,9720,4710,5010,2.063694,-1520.0,0.843621,NaN,NaN,NaN,NaN,-1524,18.10,453.0,NaN
2,에이프로젠바이오로직스,1631.0,상승 90,+5.84%,1631.0,1632.0,498832.0,802.0,155279.0,2024-05-12,003060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66575468,66575468,374036,0.56%,101.57,+0.31%,코스피,1086,887,6927,1467,5460,4.721881,-5296.0,0.235455,NaN,NaN,NaN,NaN,-1838,0.29,5607.0,NaN
3,광동헬스바이오,2710.0,상승 105,+4.03%,2610.0,2675.0,2.0,5.0,891.0,2024-05-12,086220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11086579,11086579,203906,1.84%,101.57,+0.31%,코스피,1159,753,14950,7580,7370,1.972296,-12240.0,0.181271,NaN,NaN,NaN,27.72,377,0.95,11027.0,0.48
4,대봉엘에스 *,10450.0,상승 400,+3.98%,10440.0,10450.0,203025.0,2095.0,84220.0,2024-05-12,078140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98867465,98867465,1221029,1.24%,101.57,+0.31%,코스닥,1932,455,3140,1180,1960,2.661017,7310.0,3.328025,NaN,NaN,NaN,NaN,-540,2.58,757.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,부광약품,6600.0,하락 120,-1.79%,6600.0,6610.0,184849.0,1225.0,659661.0,2024-05-12,003000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25862493,25862493,133359,0.52%,101.57,+0.31%,코스피,1922,462,11370,6290,5080,1.807631,-4770.0,0.580475,NaN,NaN,NaN,NaN,-703,2.98,2497.0,NaN
160,동아쏘시오홀딩스,105500.0,"하락 2,000",-1.86%,105500.0,105800.0,8208.0,870.0,7341.0,2024-05-12,000640,412.0,103.0,76.0,24.9,18.51,680.0,52.74,11229930,11229930,534472,4.76%,101.57,+0.31%,코스피,3796,215,44500,26750,17750,1.663551,61000.0,2.370787,53333.0,4.0,매수,14.61,2314,1.77,19055.0,1.55
161,에이프릴바이오 *,15190.0,하락 290,-1.87%,15190.0,15200.0,134956.0,2065.0,166529.0,2024-05-12,397030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27922396,27922396,705463,2.53%,101.57,+0.31%,코스닥,1279,685,6040,2275,3765,2.654945,9150.0,2.514901,NaN,NaN,NaN,NaN,-546,10.88,421.0,NaN
162,HLB제약 *,30400.0,하락 850,-2.72%,30350.0,30400.0,330123.0,10167.0,448576.0,2024-05-12,047920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85065562,85065562,7670858,9.02%,101.57,+0.31%,코스닥,1666,545,2220,1110,1110,2.000000,28180.0,13.693694,NaN,NaN,NaN,NaN,-110,0.86,2273.0,NaN
163,씨엔알리서치 *,1768.0,하락 51,-2.80%,1767.0,1768.0,2015844.0,3553.0,1546839.0,2024-05-12,359090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20467248,20467248,728512,3.56%,101.57,+0.31%,코스닥,572,1242,10200,2060,8140,4.951456,-8432.0,0.173333,NaN,NaN,NaN,NaN,-1366,2.79,1001.0,NaN